# Generated by Django 2.2.4 on 2019-09-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calcular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(max_length=200)),
                ('resultado', models.IntegerField()),
                ('fecha_de_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
