# Generated by Django 2.2.4 on 2019-09-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcular',
            name='resultado',
            field=models.IntegerField(default=0),
        ),
    ]
